version: "3.9"

services:
  nuxtapp:
    image: nuxttest:latest
    container_name: nuxtapp
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mssql-server-instance
      DB_PORT: "1433"
      DB_USER: frame
      DB_PASSWORD: frame
      DB_NAME: theframework
      DB_TRUST_SERVER_CERT: "true"
      # 필요 시 주석 해제하여 DB 초기화 스킵
      # SKIP_DB_INIT: "true"
    networks:
      - nuxtnet
    restart: "no"

networks:
  nuxtnet:
    external: true

